config/routes.rb
WelcomeHome::Application.routes.draw do
  resources :users
  resources :current_users, only: [:index]
  match '/heavyrotation' => "music#heavyrotation", :as => :heavyrotation
  match '/login' => "music#login", :as => :login
  match '/logout' => "music#logout", :as => :logout
  match '/callback' => "music#callback", :as => :callback
  root :to => 'users#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :mac, :themesong_url, :rdio_user, :device_name
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to :controller => 'users', :action => 'index'
    else
      render :action => 'edit'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.error_messages %>
  <div class="field">
    <%= f.text_field :name, placeholder: 'Your Name' %>
  </div>
  <div class="field">
    <%= f.text_field :rdio_user, placeholder: 'Your Rdio User ID' %>
  </div>
  <div class="action"><%= f.submit %></div>
<% end %>

app/views/users/edit.html.erb
<% title "Edit User" %>

<section class="edit-user">
  <%= render 'form' %>
</section>

app/views/users/index.html.erb
<%=  %>
<h1>Music: The Gathering</h1>

<script>
  var interval = setInterval(function () {
    updateUsers(users_json);
  }, 1500);
</script>

<section class="users"></section>

<section class="playlist">
  <div class="playlist-header"><!--
 --><span>Track</span><!--
 --><span>Artist</span><!--
 --><span>User</span>
  </div>
  <ul>
  </ul>
  <div id="api">

  </div>
</section>

app/views/users/new.html.erb
<% title "New User" %>

<%= render 'form' %>

<p><%= link_to "Back to List", users_path %></p>

app/views/users/show.html.erb
<% title "User" %>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>
<p>
  <strong>Mac:</strong>
  <%= @user.mac %>
</p>
<p>
  <strong>Themesong Url:</strong>
  <%= link_to @user.themesong_url %>
</p>
<p>
  <strong>RDIO User:</strong>
  <%= @user.rdio_user %>
</p>
<p>
  <strong>Device Name:</strong>
  <%= @user.device_name %>
</p>
<p>
  <%= link_to "Edit", edit_user_path(@user) %> |
  <%= link_to "Destroy", @user, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", users_path %>
</p>